name: Theme CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install PHPCS + WPCS
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require wp-coding-standards/wpcs:"^3"
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Install Theme Check CLI
        run: |
          npm i -g @wordpress/theme-check

      - name: Create reports directory
        run: mkdir -p .reports

      - name: Run Theme Check (JSON)
        run: |
          theme-check . --format json > .reports/theme-check.json || true

      - name: Run PHPCS (JSON)
        run: |
          ~/.composer/vendor/bin/phpcs -q --standard=WordPress,WordPress-Docs,WordPress-Extra --report=json . > .reports/phpcs.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: theme-reports
          path: .reports
